Repository AndreasPB/aa-final-project-stuff, pull requests merged in 2022-05, with the labels that each got.

#1 Add latex template
  .gitignore
  report/report.pdf
  report/report.tex
Labels: documentation

#10 Add review vote plot
  poetry.lock
  pyproject.toml
  vote_plot.ipynb
  vote_plot.py
Labels: enhancement

#13 Move files out of root
  amazon.py
  five_star_wordcloud.png
  one_star_wordcloud.png
  report/img/five_star_wordcloud.png
  report/img/one_star_wordcloud.png
  src/amazon.ipynb
  src/amazon.py
  src/amazon_cleanup.ipynb
  src/amazon_cleanup.py
  src/rating_plots.ipynb
  src/rating_plots.py
  src/vote_plot.ipynb
  src/vote_plot.py
  src/wordclouds.ipynb
  src/wordclouds.py
  vote_plot.ipynb
  wordcloud.ipynb
Labels: enhancement

#21 Implement document-term matrix
  poetry.lock
  src/better_success_metric.ipynb
  src/better_success_metric.py
  src/term_matrix.ipynb
  src/term_matrix.py
Labels: enhancement

#27 Refactor and clean-up
  src/amazon_cleanup.ipynb
  src/amazon_cleanup.py
  src/better_success_metric.ipynb
  src/better_success_metric.py
  src/term_matrix.ipynb
  src/term_matrix.py
  src/vote_plot.ipynb
  src/vote_plot.py
Labels: enhancement

#24 TF-IDF
  src/1_preprocess/cleanup.ipynb
  src/1_preprocess/cleanup.py
  src/1_preprocess/success_metric.ipynb
  src/1_preprocess/success_metric.py
  src/2_train/term_matrix.ipynb
  src/2_train/term_matrix.py
  src/2_train/tfidf.ipynb
  src/2_train/tfidf.py
  src/amazon.ipynb
  src/amazon.py
  src/better_success_metric.ipynb
  src/plots/rating_plots.ipynb
  src/plots/rating_plots.py
  src/plots/vote_plot.ipynb
  src/plots/vote_plot.py
  src/plots/wordclouds.ipynb
  src/plots/wordclouds.py
  src/term_matrix.ipynb
  src/vote_plot.ipynb
Labels: enhancement

#37 Export plots to .svg and toggleable exporting
  report/img/no_votes_vs_votes.svg
  report/img/rating_distribution.svg
  report/img/rating_vote_heatmap_excluding_no_votes.svg
  report/img/votes_binned_excluding_0.svg
  report/img/votes_binned_including_0.svg
  src/plots/rating_plots.ipynb
  src/plots/rating_plots.py
  src/plots/vote_plot.ipynb
  src/plots/vote_plot.py
  src/plots/wordclouds.ipynb
  src/plots/wordclouds.py
Labels: documentation, enhancement

#36 Add NN MLP Classifier, confusion matrix and balanced acc score
  src/2_train/term_matrix.ipynb
  src/2_train/term_matrix.py
  src/2_train/tfidf.ipynb
  src/2_train/tfidf.py
  src/2_train/util.py
Labels: enhancement

#41 Added data cleanup subsection to Analysis section
  report/report.tex
Labels: enhancement

#38 Tweak hyper-parameters on RandomForestClassifier + add notebook text
  src/2_train/term_matrix.ipynb
  src/2_train/term_matrix.py
  src/2_train/tfidf.ipynb
  src/2_train/tfidf.py
Labels: enhancement

#44 Latexindent?
  .gitignore
  .pre-commit-config.yaml
  report/report.tex
Labels: documentation

#45 Black
  .pre-commit-config.yaml
  src/1_preprocess/cleanup.ipynb
  src/1_preprocess/cleanup.py
  src/1_preprocess/sentiment.ipynb
  src/1_preprocess/sentiment.py
  src/2_train/term_matrix.ipynb
  src/2_train/term_matrix.py
  src/2_train/tfidf.ipynb
  src/2_train/tfidf.py
  src/plots/rating_plots.ipynb
  src/plots/wordclouds.ipynb
Labels: enhancement

#40 Write analysis section - exploratory data analysis
  report/img/no_votes_vs_votes.pdf
  report/img/rating_distribution.pdf
  report/img/rating_vote_heatmap_excluding_no_votes.pdf
  report/img/votes_binned_excluding_0.pdf
  report/report.tex
Labels: enhancement

#43 DNN MLP Analysis + Table
  .gitignore
  report/report.tex
Labels: documentation

#51 Add Logistic Regression model building text
  report/report.tex
Labels: documentation, enhancement

#17 Write conclusion
  report/report.tex
Labels: documentation, enhancement

#47 Write data visualization section
  report/img/unclean_data.pdf
  report/report.tex
Labels: enhancement

#56 Add references to Logistic Regression and LinearSVC
  report/report.tex
Labels: documentation

#60 TEMP NOT BROKEN YET, MUST GO FURTHER BEYOND
  report/report.pdf
  report/report.tex
Labels: documentation, enhancement
